In [3]:
import pandas as pd

In [4]:
import matplotlib.pyplot as plt

In [39]:
from sklearn.preprocessing import LabelEncoder,OrdinalEncoder

In [5]:
Data=pd.read_csv("C:/Users/MithraVintha/Downloads/Shopping_Customer_Dataset (1).csv")

In [6]:
Data.head()

,Gender,Product_Category,Payment_Method,Membership_Level,City,Customer_Rating,Total_Items
0,Male,Beauty,Cash,Premium,Chicago,4.6,8
1,Female,Home & Kitchen,PayPal,Bronze,Chicago,4.2,2
2,Female,Sports,Debit Card,Silver,Miami,3.7,9
3,Female,Electronics,Cash,Silver,New York,3.7,5
4,Male,Sports,PayPal,Silver,Los Angeles,4.8,10

In [7]:
Data.tail()

,Gender,Product_Category,Payment_Method,Membership_Level,City,Customer_Rating,Total_Items
995,Male,Clothing,Credit Card,Bronze,Houston,4.0,7
996,Female,Beauty,Credit Card,Silver,Houston,2.1,7
997,Male,Sports,Debit Card,Silver,Miami,2.3,8
998,Female,Beauty,PayPal,Gold,Houston,4.7,2
999,Male,Home & Kitchen,PayPal,Silver,Miami,1.2,9

In [8]:
Data.shape

(1000, 7)

In [9]:
Data.size

7000

In [10]:
Data.columns

Index(['Gender', 'Product_Category', 'Payment_Method', 'Membership_Level',
       'City', 'Customer_Rating', 'Total_Items'],
      dtype='object')

In [11]:
Data.isnull()

,Gender,Product_Category,Payment_Method,Membership_Level,City,Customer_Rating,Total_Items
0,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False

In [12]:
Data.dropna()

,Gender,Product_Category,Payment_Method,Membership_Level,City,Customer_Rating,Total_Items
0,Male,Beauty,Cash,Premium,Chicago,4.6,8
1,Female,Home & Kitchen,PayPal,Bronze,Chicago,4.2,2
2,Female,Sports,Debit Card,Silver,Miami,3.7,9
3,Female,Electronics,Cash,Silver,New York,3.7,5
4,Male,Sports,PayPal,Silver,Los Angeles,4.8,10
...,...,...,...,...,...,...,...
995,Male,Clothing,Credit Card,Bronze,Houston,4.0,7
996,Female,Beauty,Credit Card,Silver,Houston,2.1,7
997,Male,Sports,Debit Card,Silver,Miami,2.3,8
998,Female,Beauty,PayPal,Gold,Houston,4.7,2
999,Male,Home & Kitchen,PayPal,Silver,Miami,1.2,9

In [13]:
Data.dropna(inplace=True)

In [14]:
print(Data)

     Gender Product_Category Payment_Method Membership_Level         City  \
0      Male           Beauty           Cash          Premium      Chicago
1    Female   Home & Kitchen         PayPal           Bronze      Chicago
2    Female           Sports     Debit Card           Silver        Miami
3    Female      Electronics           Cash           Silver     New York
4      Male           Sports         PayPal           Silver  Los Angeles
..      ...              ...            ...              ...          ...
995    Male         Clothing    Credit Card           Bronze      Houston
996  Female           Beauty    Credit Card           Silver      Houston
997    Male           Sports     Debit Card           Silver        Miami
998  Female           Beauty         PayPal             Gold      Houston
999    Male   Home & Kitchen         PayPal           Silver        Miami

     Customer_Rating  Total_Items
0                4.6            8
1                4.2            2
2                3.7            9
3                3.7            5
4                4.8           10
..               ...          ...
995              4.0            7
996              2.1            7
997              2.3            8
998              4.7            2
999              1.2            9

[945 rows x 7 columns]

In [20]:
Data["Total_Items"] = pd.to_datetime(Data["Total_Items"], errors="coerce")
Data.head()

,Gender,Product_Category,Payment_Method,Membership_Level,City,Customer_Rating,Total_Items
0,Male,Beauty,Cash,Premium,Chicago,4.6,1970-01-01 00:00:00.000000008
1,Female,Home & Kitchen,PayPal,Bronze,Chicago,4.2,1970-01-01 00:00:00.000000002
2,Female,Sports,Debit Card,Silver,Miami,3.7,1970-01-01 00:00:00.000000009
3,Female,Electronics,Cash,Silver,New York,3.7,1970-01-01 00:00:00.000000005
4,Male,Sports,PayPal,Silver,Los Angeles,4.8,1970-01-01 00:00:00.000000010

In [16]:
Data.loc[0:3,["Gender","City"]]

   Gender      City
0    Male   Chicago
1  Female   Chicago
2  Female     Miami
3  Female  New York

In [17]:
Data[(Data['Total_Items'] > 15) & (Data['Total_Items'] < 10)]
Data.head()

,Gender,Product_Category,Payment_Method,Membership_Level,City,Customer_Rating,Total_Items
0,Male,Beauty,Cash,Premium,Chicago,4.6,8
1,Female,Home & Kitchen,PayPal,Bronze,Chicago,4.2,2
2,Female,Sports,Debit Card,Silver,Miami,3.7,9
3,Female,Electronics,Cash,Silver,New York,3.7,5
4,Male,Sports,PayPal,Silver,Los Angeles,4.8,10

In [25]:
Data.iloc[0:3]

,Gender,Product_Category,Payment_Method,Membership_Level,City,Customer_Rating,Total_Items
0,Male,Beauty,Cash,Premium,Chicago,4.6,1970-01-01 00:00:00.000000008
1,Female,Home & Kitchen,PayPal,Bronze,Chicago,4.2,1970-01-01 00:00:00.000000002
2,Female,Sports,Debit Card,Silver,Miami,3.7,1970-01-01 00:00:00.000000009

In [27]:
Data[Data["Customer_Rating"]< 4.6]
Data[Data["Customer_Rating"]>= 4.6]
Data[Data["Customer_Rating"]<= 4.6]

,Gender,Product_Category,Payment_Method,Membership_Level,City,Customer_Rating,Total_Items
0,Male,Beauty,Cash,Premium,Chicago,4.6,1970-01-01 00:00:00.000000008
1,Female,Home & Kitchen,PayPal,Bronze,Chicago,4.2,1970-01-01 00:00:00.000000002
2,Female,Sports,Debit Card,Silver,Miami,3.7,1970-01-01 00:00:00.000000009
3,Female,Electronics,Cash,Silver,New York,3.7,1970-01-01 00:00:00.000000005
5,Male,Electronics,Debit Card,Silver,Chicago,2.2,1970-01-01 00:00:00.000000006
...,...,...,...,...,...,...,...
994,Male,Clothing,PayPal,Bronze,Los Angeles,2.9,1970-01-01 00:00:00.000000003
995,Male,Clothing,Credit Card,Bronze,Houston,4.0,1970-01-01 00:00:00.000000007
996,Female,Beauty,Credit Card,Silver,Houston,2.1,1970-01-01 00:00:00.000000007
997,Male,Sports,Debit Card,Silver,Miami,2.3,1970-01-01 00:00:00.000000008
999,Male,Home & Kitchen,PayPal,Silver,Miami,1.2,1970-01-01 00:00:00.000000009

In [31]:
Data["CR"] = Data["Customer_Rating"]*2
Data.head()

,Gender,Product_Category,Payment_Method,Membership_Level,City,Customer_Rating,Total_Items,CR
0,Male,Beauty,Cash,Premium,Chicago,4.6,1970-01-01 00:00:00.000000008,9.2
1,Female,Home & Kitchen,PayPal,Bronze,Chicago,4.2,1970-01-01 00:00:00.000000002,8.4
2,Female,Sports,Debit Card,Silver,Miami,3.7,1970-01-01 00:00:00.000000009,7.4
3,Female,Electronics,Cash,Silver,New York,3.7,1970-01-01 00:00:00.000000005,7.4
4,Male,Sports,PayPal,Silver,Los Angeles,4.8,1970-01-01 00:00:00.000000010,9.6

In [32]:
Data.groupby("Payment_Method")["CR"].mean()

Payment_Method
Cash           6.014978
Credit Card    5.994805
Debit Card     5.976654
PayPal         5.806087
Name: CR, dtype: float64

In [33]:
Data['Gender'].unique()

array(['Male', 'Female'], dtype=object)

In [40]:
Dt = OrdinalEncoder()

In [48]:
Dt = OrdinalEncoder(categories=[['Cash', 'Credit Card', 'Debit Card', 'PayPal']])
Data["PM1"] = Dt.fit_transform(Data[['Payment_Method']])
Data.head()

,Gender,Product_Category,Payment_Method,Membership_Level,City,Customer_Rating,Total_Items,CR,PM1
0,Male,Beauty,Cash,Premium,Chicago,4.6,1970-01-01 00:00:00.000000008,9.2,0.0
1,Female,Home & Kitchen,PayPal,Bronze,Chicago,4.2,1970-01-01 00:00:00.000000002,8.4,3.0
2,Female,Sports,Debit Card,Silver,Miami,3.7,1970-01-01 00:00:00.000000009,7.4,2.0
3,Female,Electronics,Cash,Silver,New York,3.7,1970-01-01 00:00:00.000000005,7.4,0.0
4,Male,Sports,PayPal,Silver,Los Angeles,4.8,1970-01-01 00:00:00.000000010,9.6,3.0

In [49]:
Td = LabelEncoder()

In [52]:
Data["Product_Category2"] = Td.fit_transform(Data["Product_Category"])
Data.head()

,Gender,Product_Category,Payment_Method,Membership_Level,City,Customer_Rating,Total_Items,CR,PM1,Product_Category2
0,Male,Beauty,Cash,Premium,Chicago,4.6,1970-01-01 00:00:00.000000008,9.2,0.0,0
1,Female,Home & Kitchen,PayPal,Bronze,Chicago,4.2,1970-01-01 00:00:00.000000002,8.4,3.0,3
2,Female,Sports,Debit Card,Silver,Miami,3.7,1970-01-01 00:00:00.000000009,7.4,2.0,4
3,Female,Electronics,Cash,Silver,New York,3.7,1970-01-01 00:00:00.000000005,7.4,0.0,2
4,Male,Sports,PayPal,Silver,Los Angeles,4.8,1970-01-01 00:00:00.000000010,9.6,3.0,4

In [54]:
Data = pd.get_dummies(Data,columns=['Gender'])
Data.head()

,Product_Category,Payment_Method,Membership_Level,City,Customer_Rating,Total_Items,CR,Product_Category2,PM1_0.0,PM1_1.0,PM1_2.0,PM1_3.0,Gender_Female,Gender_Male
0,Beauty,Cash,Premium,Chicago,4.6,1970-01-01 00:00:00.000000008,9.2,0,True,False,False,False,False,True
1,Home & Kitchen,PayPal,Bronze,Chicago,4.2,1970-01-01 00:00:00.000000002,8.4,3,False,False,False,True,True,False
2,Sports,Debit Card,Silver,Miami,3.7,1970-01-01 00:00:00.000000009,7.4,4,False,False,True,False,True,False
3,Electronics,Cash,Silver,New York,3.7,1970-01-01 00:00:00.000000005,7.4,2,True,False,False,False,True,False
4,Sports,PayPal,Silver,Los Angeles,4.8,1970-01-01 00:00:00.000000010,9.6,4,False,False,False,True,False,True